### ISSUE TITLE
chart.mjs shows "failed to load module script" message. What should we do to solve this?

### ISSUE THREAD

**Issue by tosintech-web** [petersphilo/humhub-social_stats#5]
When we access "social stats" menu on Admin menu, these messages are shown on Developer tools of Browser (chrome).
![スクリーンショット 2022-10-07 173020](https://user-images.githubusercontent.com/75475434/194509296-73aaf562-1f03-4667-a532-82cd1e8d9a5f.png)

**Comment by petersphilo** [comment]
i'm not sure what to do about those messages..
i'm aware of them, and have yet to find a solution..
i'm working on it..

**Comment by petersphilo** [comment]
The best thing to do in order to resolve this issue is to add the following line to the _root .htaccess_ file:
`AddType text/javascript .mjs`

**Comment by tosintech-web** [comment]
OK, I running with Nginx. So, I add mime types statement on Nginx conf file.
Thank you.
