### ISSUE TITLE
No data populated after ~5days

### ISSUE THREAD

**Issue by samuk** [petersphilo/humhub-social_stats#8]
I installed the plugin around five days ago but I'm not seeing any data yet. Is there any log/config files I can check?

**Comment by marc-farre** [comment]
I think the bug is from javascript. On my side, it occurs when I come back a second time on the page. But refreshing it shows the data.

**Comment by samuk** [comment]
Ah in my case it was my adblocker

**Comment by marc-farre** [comment]
Yes, there are 2 problems:
- when you come back a second time on the page (without refreshing, by browsing on Humhub), the JS is not loaded correctly (with pjax)
- some datas are loaded from `paypalobjects.com` so if you have an add blocker it's not loaded and the JS doesn't work. On Humhub, the good practice is to have all JS in the module (no external dependencies)
